# Generated by Django 4.0 on 2022-01-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url_name', models.CharField(blank=True, max_length=200, unique=True)),
                ('ducats', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('primeset_name', models.CharField(max_length=200)),
                ('primeset_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
